/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectfolder;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROGUE
 */
public class addTable extends javax.swing.JFrame {
    
    SearchHotel sc;
    private int price;
    private long contact;
    
    /**
     * Creates new form addTable
     */
    public addTable() {
        initComponents();
        sc = new SearchHotel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu3 = new javax.swing.JMenu();
        sidePanel = new javax.swing.JPanel();
        btnSearchHotel = new javax.swing.JButton();
        btnAddData = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLoginPage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lbContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lbRating = new javax.swing.JLabel();
        lbCategory = new javax.swing.JLabel();
        btnAddToTable = new javax.swing.JButton();
        rBtnOne = new javax.swing.JRadioButton();
        rBtnThree = new javax.swing.JRadioButton();
        rBtnFive = new javax.swing.JRadioButton();
        checkAirportHotel = new javax.swing.JCheckBox();
        checkStayHotel = new javax.swing.JCheckBox();
        checkBusinessHotel = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miopen = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 850));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 850));

        sidePanel.setBackground(new java.awt.Color(0, 78, 146));

        btnSearchHotel.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchHotel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSearchHotel.setForeground(new java.awt.Color(0, 78, 146));
        btnSearchHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/AddTable/search table icon.png"))); // NOI18N
        btnSearchHotel.setText("   Search Hotel");
        btnSearchHotel.setBorder(null);
        btnSearchHotel.setBorderPainted(false);
        btnSearchHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHotelActionPerformed(evt);
            }
        });

        btnAddData.setBackground(new java.awt.Color(255, 255, 255));
        btnAddData.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAddData.setForeground(new java.awt.Color(0, 78, 146));
        btnAddData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/AddTable/add to.png"))); // NOI18N
        btnAddData.setText("    Add Data");
        btnAddData.setBorder(null);
        btnAddData.setBorderPainted(false);
        btnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 78, 146));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/AddTable/exit icon.png"))); // NOI18N
        btnExit.setText("     Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginPage.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnLoginPage.setForeground(new java.awt.Color(0, 78, 146));
        btnLoginPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/AddTable/login icons.png"))); // NOI18N
        btnLoginPage.setText("   Login Page");
        btnLoginPage.setBorder(null);
        btnLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnSearchHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        table.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Price", "Contact", "Rating", "Category"
            }
        ));
        jScrollPane1.setViewportView(table);

        lbName.setBackground(new java.awt.Color(255, 255, 255));
        lbName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbName.setText("       Name :");

        txtName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 78, 146));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 78, 146)));

        lbLocation.setBackground(new java.awt.Color(255, 255, 255));
        lbLocation.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbLocation.setText("    Location :");

        txtLocation.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(0, 78, 146));
        txtLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLocation.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 78, 146)));

        lbContact.setBackground(new java.awt.Color(255, 255, 255));
        lbContact.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbContact.setText("      Contact :");

        txtContact.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtContact.setForeground(new java.awt.Color(0, 78, 146));
        txtContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 78, 146)));

        lbPrice.setBackground(new java.awt.Color(255, 255, 255));
        lbPrice.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbPrice.setText("         Price :");

        txtPrice.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 78, 146));
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 78, 146)));

        lbRating.setBackground(new java.awt.Color(255, 255, 255));
        lbRating.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbRating.setText("        Rating :");

        lbCategory.setBackground(new java.awt.Color(255, 255, 255));
        lbCategory.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbCategory.setText("     Category :");

        btnAddToTable.setBackground(new java.awt.Color(0, 78, 146));
        btnAddToTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAddToTable.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/AddTable/add icon.png"))); // NOI18N
        btnAddToTable.setText("    Add To Table");
        btnAddToTable.setBorder(null);
        btnAddToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToTableActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnOne);
        rBtnOne.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rBtnOne.setText("1");

        buttonGroup1.add(rBtnThree);
        rBtnThree.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rBtnThree.setText("3");
        rBtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnThreeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnFive);
        rBtnFive.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rBtnFive.setText("5");

        checkAirportHotel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        checkAirportHotel.setText("Airport Hotel");

        checkStayHotel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        checkStayHotel.setText("Stay Hotel");

        checkBusinessHotel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        checkBusinessHotel.setText("Business Hotel");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 78, 146));
        jLabel1.setText("Hotel Information System");

        mFile.setText("File");

        miopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miopen.setText("Open");
        miopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miopenActionPerformed(evt);
            }
        });
        mFile.add(miopen);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        jMenuBar1.add(mFile);

        mHelp.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mHelp.add(jMenuItem1);

        jMenuBar1.add(mHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnAddToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rBtnOne)
                                                .addGap(18, 18, 18)
                                                .addComponent(rBtnThree)
                                                .addGap(18, 18, 18)
                                                .addComponent(rBtnFive))
                                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkAirportHotel)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkStayHotel)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkBusinessHotel)))))
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnAddToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnOne)
                    .addComponent(rBtnFive)
                    .addComponent(rBtnThree))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAirportHotel)
                    .addComponent(checkStayHotel)
                    .addComponent(checkBusinessHotel))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHotelActionPerformed
        new SearchHotel().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSearchHotelActionPerformed

    private void btnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDataActionPerformed

    }//GEN-LAST:event_btnAddDataActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPageActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLoginPageActionPerformed

    public void ExportFromTable(){
        String path = "src/projectfolder/file.txt";
        File file = new File(path);
        try {
            FileWriter fw = new FileWriter(file, true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0; i<table.getRowCount(); i++){
                for(int j=0; j<table.getColumnCount(); j++){
                  bw.write(table.getValueAt(i,j).toString() + " ");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "IO Exception occurs");
        }
    }
    
    private void btnAddToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToTableActionPerformed
        if(!txtName.getText().isEmpty() && !txtLocation.getText().isEmpty() && !txtPrice.getText().isEmpty() && !txtContact.getText().isEmpty()){
            String hotelName = txtName.getText();
            String location = txtLocation.getText();
            try{
                price = Integer.parseInt(txtPrice.getText());
                contact = Long.parseLong(txtContact.getText());
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(this,"Please enter numeric value on price and contact");
            }
            
            String rating;
            if(rBtnOne.isSelected()){
                rating = "1";
            }else if(rBtnThree.isSelected()){
                rating = "3";
            }else if(rBtnFive.isSelected()){
                rating = "5";
            }else{
                rating = "";
            }
            
            String category;
            
            if(checkAirportHotel.isSelected()){
                category = "Airport";
            }else if(checkStayHotel.isSelected()){
                category = "Stay";
            }else if(checkBusinessHotel.isSelected()){
                category = "Business";
            }
            else{
                category = "Not_Defined";
            }
                    
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            String values[] = {hotelName,location,String.valueOf(price),String.valueOf(contact),rating, category};
            int rowCount= table.getRowCount();
            for(int i=0; i<rowCount; i++){
                String checkName = (String) table.getValueAt(i,0);
                String checkLocation = (String) table.getValueAt(i,1);
                if(checkName.equals(hotelName) && checkLocation.equals(location)){
                    JOptionPane.showMessageDialog(this,"This hotel is already added");
                    return;
                }               
            }
            if(!Pattern.compile("98[0-9]{8}").matcher(String.valueOf(contact)).matches()){
                    JOptionPane.showMessageDialog(this,"This contact is invalid");
                    return;
            }
                dtm.addRow(values);
                HotelData d = new HotelData(hotelName,location,price,contact,rating,category);
                sc.getList().add(d);
                ExportFromTable();
        }else{
            JOptionPane.showMessageDialog(this,"Please fill all empty fields");
        }
           
    }//GEN-LAST:event_btnAddToTableActionPerformed

    private void rBtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnThreeActionPerformed

    private void miopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miopenActionPerformed
        importToTable();
    }//GEN-LAST:event_miopenActionPerformed

    public void importToTable(){
        String path = "src/projectfolder/file.txt";
        File file = new File(path);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            
            String row = "";
            while ((row = br.readLine()) != null) {
                String values[] = row.split(" ");
                model.addRow(values);
                HotelData hData = new HotelData(values[0], values[1], Integer.parseInt(values[2]), Long.parseLong(values[3]), values[4], values[5]);
                sc.getList().add(hData);
            }
        
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "This file is not found");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "IO Exception occurs");
        }
    }
    
    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " +"src\\projectfolder\\help.txt");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddData;
    private javax.swing.JButton btnAddToTable;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoginPage;
    private javax.swing.JButton btnSearchHotel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkAirportHotel;
    private javax.swing.JCheckBox checkBusinessHotel;
    private javax.swing.JCheckBox checkStayHotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbContact;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbRating;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miopen;
    private javax.swing.JRadioButton rBtnFive;
    private javax.swing.JRadioButton rBtnOne;
    private javax.swing.JRadioButton rBtnThree;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
