/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectfolder;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROGUE
 */
public class SearchHotel extends javax.swing.JFrame {
    ArrayList<HotelData> aList = new ArrayList<HotelData>();
    
    public ArrayList getList(){
        return aList;
    }

    /**
     * Creates new form Login
     */
    public SearchHotel() {
        initComponents();
    }
    
    public String abc(int i) {
        String word ="HotelName : "+aList.get(i).getHotelName()+ "\nLocation : "+aList.get(i).getLocation() + "\nPrice : "+aList.get(i).getPrice() + "\nContact : "+aList.get(i).getContact() + "\nRating : "+aList.get(i).getRating() + "\nCategory : "+aList.get(i).getCategory();
        return word;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidePanel = new javax.swing.JPanel();
        btnSearchHotel = new javax.swing.JButton();
        btnAddData = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLoginPage = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        comboSelect = new javax.swing.JComboBox<>();
        checkAirportHotel = new javax.swing.JCheckBox();
        checkBusinessHotel = new javax.swing.JCheckBox();
        btnSearchByCategory = new javax.swing.JButton();
        checkStayHotel = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 850));

        sidePanel.setBackground(new java.awt.Color(0, 78, 146));

        btnSearchHotel.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchHotel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSearchHotel.setForeground(new java.awt.Color(0, 78, 146));
        btnSearchHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/Search Table/search table icon.png"))); // NOI18N
        btnSearchHotel.setText("   Search Hotel");
        btnSearchHotel.setBorder(null);
        btnSearchHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHotelActionPerformed(evt);
            }
        });

        btnAddData.setBackground(new java.awt.Color(255, 255, 255));
        btnAddData.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAddData.setForeground(new java.awt.Color(0, 78, 146));
        btnAddData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/Search Table/add to.png"))); // NOI18N
        btnAddData.setText("    Add Data");
        btnAddData.setBorder(null);
        btnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 78, 146));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/Search Table/exit icon.png"))); // NOI18N
        btnExit.setText("     Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLoginPage.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginPage.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnLoginPage.setForeground(new java.awt.Color(0, 78, 146));
        btnLoginPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfolder/pictures/Search Table/login icons.png"))); // NOI18N
        btnLoginPage.setText("   Login Page");
        btnLoginPage.setBorder(null);
        btnLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnSearchHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Price", "Contact", "Rating", "Category"
            }
        ));
        jScrollPane1.setViewportView(table);

        txtSearch.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 78, 146));
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 78, 146)));

        btnSearch.setBackground(new java.awt.Color(0, 78, 146));
        btnSearch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        comboSelect.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        comboSelect.setForeground(new java.awt.Color(0, 78, 146));
        comboSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By", "Hotel Name", "Location", "Price", "Rating" }));
        comboSelect.setBorder(null);

        checkAirportHotel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(checkAirportHotel);
        checkAirportHotel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        checkAirportHotel.setForeground(new java.awt.Color(0, 78, 146));
        checkAirportHotel.setText("Airport Hotel");

        checkBusinessHotel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(checkBusinessHotel);
        checkBusinessHotel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        checkBusinessHotel.setForeground(new java.awt.Color(0, 78, 146));
        checkBusinessHotel.setText("Business Hotel");

        btnSearchByCategory.setBackground(new java.awt.Color(0, 78, 146));
        btnSearchByCategory.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSearchByCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchByCategory.setText("SearchByCategory");
        btnSearchByCategory.setBorder(null);
        btnSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCategoryActionPerformed(evt);
            }
        });

        checkStayHotel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(checkStayHotel);
        checkStayHotel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        checkStayHotel.setForeground(new java.awt.Color(0, 78, 146));
        checkStayHotel.setText("Stay Hotel");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 78, 146));
        jLabel1.setText("Hotel Information System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(checkAirportHotel)
                                .addGap(18, 18, 18)
                                .addComponent(checkStayHotel)
                                .addGap(18, 18, 18)
                                .addComponent(checkBusinessHotel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchByCategory))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkAirportHotel)
                            .addComponent(checkBusinessHotel)
                            .addComponent(checkStayHotel)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnSearchByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mFile.setText("File");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpen.setText("Open");
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        mFile.add(miOpen);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        jMenuBar1.add(mFile);

        mHelp.setText("Help");
        mHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHelpActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mHelp.add(jMenuItem1);

        jMenuBar1.add(mHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPageActionPerformed
         new Login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnLoginPageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDataActionPerformed
        new addTable().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddDataActionPerformed

    private void btnSearchHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHotelActionPerformed
        
    }//GEN-LAST:event_btnSearchHotelActionPerformed
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String value = String.valueOf(comboSelect.getSelectedItem());
        String search = txtSearch.getText();
        if(value.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Please select atleast one category");
           return;
        }else {
            if(search.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter something to search");
            }
            else{
            if(value.equals("Hotel Name")) {
                SelectionSort.sortName(aList);
                
                DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                dtm.setRowCount(0);
                aList.forEach(item -> {
                    String values [] = {item.getHotelName(), item.getLocation(), String.valueOf(item.getPrice()), 
                    String.valueOf(item.getContact()), item.getRating(), item.getCategory()};
                    dtm.addRow(values);

                });
                
                BinarySearch bs = new BinarySearch();
                int i = bs.binarySearchName(aList, search);
                
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }else if(value.equals("Location")) {
                SelectionSort.sortLocation(aList);
                DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                dtm.setRowCount(0);
                aList.forEach(item -> {
                    String values [] = {item.getHotelName(), item.getLocation(), String.valueOf(item.getPrice()), 
                    String.valueOf(item.getContact()), item.getRating(), item.getCategory()};
                    dtm.addRow(values);
                });
                
                BinarySearch bs = new BinarySearch();
                int i = bs.binarySearchLocation(aList, search);
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }else if(value.equals("Price")) {
                SelectionSort.sortPrice(aList);
                DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                dtm.setRowCount(0);
                aList.forEach(item -> {
                    String values [] = {item.getHotelName(), item.getLocation(), String.valueOf(item.getPrice()), 
                    String.valueOf(item.getContact()), item.getRating(), item.getCategory()};
                    dtm.addRow(values);
                });
                
                BinarySearch bs = new BinarySearch();
                int i = bs.binarySearchPrice(aList, Integer.parseInt(search));
                
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }else if(value.equals("Rating")) {
                SelectionSort.sortRating(aList);
                DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                dtm.setRowCount(0);
                aList.forEach(item -> {
                    String values [] = {item.getHotelName(), item.getLocation(), String.valueOf(item.getPrice()), 
                    String.valueOf(item.getContact()), item.getRating(), item.getCategory()};
                    dtm.addRow(values);
                });
                
                BinarySearch bs = new BinarySearch();
                int i = bs.binarySearchRating(aList, search);
                
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }
            
        }

        } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed
          importToTable();
    }//GEN-LAST:event_miOpenActionPerformed

    public void importToTable(){
        String path = "src/projectfolder/file.txt";
        File file = new File(path);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            
            String row = "";
            while ((row = br.readLine()) != null) {
                String values[] = row.split(" ");
                model.addRow(values);
                HotelData hData = new HotelData(values[0], values[1], Integer.parseInt(values[2]), Long.parseLong(values[3]), values[4], values[5]);
                aList.add(hData);
            }
        
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "This file is not found");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "IO Exception occurs");
        }
    }
    
    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    private void btnSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCategoryActionPerformed
        if(checkAirportHotel.isSelected()){
                String search = "Airport";
                LinearSearch ls = new LinearSearch();
                int i = ls.linearSearchAirportHotel(aList, search);
                
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }
            
        else if(checkStayHotel.isSelected()){
                String search = "Stay";
                LinearSearch ls = new LinearSearch();
                int i = ls.linearSearchStayHotel(aList, search);
                
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }
            
        else if(checkBusinessHotel.isSelected()){
            String search = "Business";
            LinearSearch ls = new LinearSearch();
            int i = ls.linearSearchBusinessHotel(aList, search);
            if(search.isEmpty()){
            }    
            else{   
                 if (i == -1) {
                    JOptionPane.showMessageDialog(this, "No any Hotel data found");
                    return;
                }else {
                    String word = abc(i);
                    JOptionPane.showMessageDialog(this, word);
                }
            }
        }
    }//GEN-LAST:event_btnSearchByCategoryActionPerformed

    private void mHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHelpActionPerformed
        
    }//GEN-LAST:event_mHelpActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " +"src\\projectfolder\\help.txt");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddData;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoginPage;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchByCategory;
    private javax.swing.JButton btnSearchHotel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkAirportHotel;
    private javax.swing.JCheckBox checkBusinessHotel;
    private javax.swing.JCheckBox checkStayHotel;
    private javax.swing.JComboBox<String> comboSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
